### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by kelupa** [jbbarth/redmine_drafts#29]
Hi:
Can you replace the spanish translate?

If you want, I can make the translation.

`
es:
  label_draft_saved_time: "Bosquejo ahorrado en  %{value}"

  label_draft_pending: "Bosquejo pendiente , ahorrado %{time} hace : %{restore} o %{delete}"
`
translate to:

`
es:
  label_draft_saved_time: "Borrador guardado el  %{value}"

  label_draft_pending: "Borrador pendiente , guardado hace %{time} : %{restore} o %{delete}"`

**Comment by jbbarth** [comment]
Done in https://github.com/jbbarth/redmine_drafts/commit/6bdb742799dab182e3d7070ea690c041f3e8d0f1, thanks!
