### ISSUE TITLE
redmine 4 url : drafts/autosave give 404

### ISSUE THREAD

**Issue by jerome-salanhac** [jbbarth/redmine_drafts#31]
No problem on install.
javascript and css file are ok.
jquery method well inserted in html.
BUT.
http://my_redmine/drafts/autosave answer a "Redmine 404" error.

**Comment by nanego** [comment]
You do not provide enough information.
Which version of Redmine are you using?
Do you use the last version of the plugin (master branch)?
Do you use any other plugin?

**Comment by jerome-salanhac** [comment]
i put redmine version in subject.

more details :
Redmine version                4.0.3.stable
Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
Rails version                  5.2.2.1

plugins installed : Clipboard image paste, Redmine Lightbox 2,Sidebar Hide Plugin

hope it will help

**Comment by jerome-salanhac** [comment]
i remove and reinstall ruby, recompile. now it works.
